In [2]:
import numpy as np
np.random.normal(3,2,5)

array([-0.55196009,  1.39362699,  1.32986461,  3.83305224,  2.52110503])

random.normal gives the random number. the first number is mean and second is std and 3rd number is the size. rows and colums can be generated by specifying in paranathesis

In [3]:
np.random.normal(3,2,(4,4))

array([[ 2.41622175,  3.36796231,  4.59562288, -0.88059095],
       [ 3.53887341,  1.60911441,  4.21193867,  2.50634072],
       [ 1.70845988,  6.88827959,  0.77450067,  2.76834509],
       [ 4.53044641,  3.29624789,  3.13987419,  2.97702693]])

In [4]:
np.round(np.random.normal(3,2,5))

array([3., 4., 6., 3., 5.])

there is no decimal value if you dont specify anything and if you specify you will get decimal value

In [5]:
np.round(np.random.normal(3,2,5),3)

array([2.903, 4.992, 3.084, 1.539, 4.548])

In [6]:
a=np.round(np.random.normal(3,2,5),3)